language: android
jdk: oraclejdk8
sudo: false

android:
components:
- tools
- build-tools-26.0.2
- android-26
- extra-android-m2repository
- extra-android-support
licenses:
- android-sdk-license-.+
- '.+'

before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
#- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

替换变量值为"C:\Users\lenovo\AppData\Local\Android\Sdk\licenses\" 路径下的 android-sdk-license和android-sdk-preview-license文件中的内容
- echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "7c928e048b455a44b323aba54342415d0429c542" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
- ./gradlew assembleRelease
